# ============================================================
# DNS Blocklist Builder – Anti-Vax / Medical Disinfo
# Category: antivax
# Format: dnsmasq
# Generated: 2026-06-22
# Domains: 31
# Source: https://github.com/DanielEnki420/dns-blocklist-builder
# ============================================================
address=/aerzte-fuer-aufklaerung.de/0.0.0.0
address=/ageofautism.com/0.0.0.0
address=/childrenshealthdefense.org/0.0.0.0
address=/corona-blog.net/0.0.0.0
address=/covidvaccineinjuries.com/0.0.0.0
address=/covidvax.live/0.0.0.0
address=/dailyexpose.uk/0.0.0.0
address=/deswegen.net/0.0.0.0
address=/drrobertyoung.com/0.0.0.0
address=/endthevax.com/0.0.0.0
address=/greenmedinfo.com/0.0.0.0
address=/healthimpactnews.com/0.0.0.0
address=/humansarefree.com/0.0.0.0
address=/impfen-nein-danke.de/0.0.0.0
address=/impfkritik.de/0.0.0.0
address=/infokrieg.tv/0.0.0.0
address=/kla.tv/0.0.0.0
address=/mercola.com/0.0.0.0
address=/mwgfd.org/0.0.0.0
address=/nvic.org/0.0.0.0
address=/questioningcovid.com/0.0.0.0
address=/stopworldcontrol.com/0.0.0.0
address=/ukcolumn.org/0.0.0.0
address=/vaccinationinformationnetwork.com/0.0.0.0
address=/vaccine-injury.info/0.0.0.0
address=/vaccinedamage.news/0.0.0.0
address=/vaccineimpact.com/0.0.0.0
address=/vaxtruth.org/0.0.0.0
address=/vaxxed.com/0.0.0.0
address=/whale.to/0.0.0.0
address=/worlddoctorsalliance.com/0.0.0.0
