# ============================================================
# DNS Blocklist Builder – Chinese State Propaganda
# Category: chinese_state
# Format: Unbound
# Generated: 2026-07-06
# Domains: 33
# Source: https://github.com/DanielEnki420/dns-blocklist-builder
# ============================================================
local-zone: "81.cn." static
local-zone: "cctv.com." static
local-zone: "cctv.net." static
local-zone: "cgtn.com." static
local-zone: "cgtn.eu." static
local-zone: "chinadaily.com.cn." static
local-zone: "chinafocus.com." static
local-zone: "chinamil.com.cn." static
local-zone: "chinanews.com.cn." static
local-zone: "cri.cn." static
local-zone: "ecns.cn." static
local-zone: "globaltimes.cn." static
local-zone: "guancha.cn." static
local-zone: "hkcd.com." static
local-zone: "huanqiu.com." static
local-zone: "legaldaily.com.cn." static
local-zone: "mod.gov.cn." static
local-zone: "news.cn." static
local-zone: "pandaily.com." static
local-zone: "people.cn." static
local-zone: "people.com.cn." static
local-zone: "pladaily.com.cn." static
local-zone: "qstheory.cn." static
local-zone: "radii.co." static
local-zone: "shine.cn." static
local-zone: "sixthtone.com." static
local-zone: "stdaily.com." static
local-zone: "takungpao.com." static
local-zone: "thepaper.cn." static
local-zone: "wenweipo.com." static
local-zone: "xinhuanet.com." static
local-zone: "xuexi.cn." static
