# ============================================================
# DNS Blocklist Builder – Chinese State Propaganda
# Category: chinese_state
# Format: dnsmasq
# Generated: 2026-07-06
# Domains: 33
# Source: https://github.com/DanielEnki420/dns-blocklist-builder
# ============================================================
address=/81.cn/0.0.0.0
address=/cctv.com/0.0.0.0
address=/cctv.net/0.0.0.0
address=/cgtn.com/0.0.0.0
address=/cgtn.eu/0.0.0.0
address=/chinadaily.com.cn/0.0.0.0
address=/chinafocus.com/0.0.0.0
address=/chinamil.com.cn/0.0.0.0
address=/chinanews.com.cn/0.0.0.0
address=/cri.cn/0.0.0.0
address=/ecns.cn/0.0.0.0
address=/globaltimes.cn/0.0.0.0
address=/guancha.cn/0.0.0.0
address=/hkcd.com/0.0.0.0
address=/huanqiu.com/0.0.0.0
address=/legaldaily.com.cn/0.0.0.0
address=/mod.gov.cn/0.0.0.0
address=/news.cn/0.0.0.0
address=/pandaily.com/0.0.0.0
address=/people.cn/0.0.0.0
address=/people.com.cn/0.0.0.0
address=/pladaily.com.cn/0.0.0.0
address=/qstheory.cn/0.0.0.0
address=/radii.co/0.0.0.0
address=/shine.cn/0.0.0.0
address=/sixthtone.com/0.0.0.0
address=/stdaily.com/0.0.0.0
address=/takungpao.com/0.0.0.0
address=/thepaper.cn/0.0.0.0
address=/wenweipo.com/0.0.0.0
address=/xinhuanet.com/0.0.0.0
address=/xuexi.cn/0.0.0.0
