# ============================================================
# DNS Blocklist Builder – Russian Propaganda
# Category: rt
# Format: Unbound
# Generated: 2026-05-11
# Domains: 50
# Source: https://github.com/DanielEnki420/dns-blocklist-builder
# ============================================================
local-zone: "anna-news.info." static
local-zone: "baltnews.com." static
local-zone: "cont.ws." static
local-zone: "de.rt.com." static
local-zone: "e-news.su." static
local-zone: "eurasia.expert." static
local-zone: "fondsk.ru." static
local-zone: "geopolitika.news." static
local-zone: "globalresearch.ca." static
local-zone: "imperiya.by." static
local-zone: "inforeactor.ru." static
local-zone: "inotv.rt.com." static
local-zone: "katehon.com." static
local-zone: "life.ru." static
local-zone: "nahnews.org." static
local-zone: "polit.info." static
local-zone: "politros.com." static
local-zone: "realtribune.ru." static
local-zone: "regnum.ru." static
local-zone: "ren.tv." static
local-zone: "rg.ru." static
local-zone: "ria.ru." static
local-zone: "riafan.ru." static
local-zone: "rt.com." static
local-zone: "rt.de." static
local-zone: "rt.fr." static
local-zone: "rt.ru." static
local-zone: "rt.uk." static
local-zone: "rubaltic.ru." static
local-zone: "rusnext.ru." static
local-zone: "rusplt.ru." static
local-zone: "russia-insider.com." static
local-zone: "russland.news." static
local-zone: "rusvesna.su." static
local-zone: "slavyangrad.org." static
local-zone: "sputnik-news.de." static
local-zone: "sputnik.by." static
local-zone: "sputnikglobe.com." static
local-zone: "sputniknews.com." static
local-zone: "sputniknews.fr." static
local-zone: "sputniknews.lat." static
local-zone: "stalkerzone.org." static
local-zone: "svpressa.ru." static
local-zone: "tass.com." static
local-zone: "tass.ru." static
local-zone: "topwar.ru." static
local-zone: "tsargrad.tv." static
local-zone: "ukraina.ru." static
local-zone: "vesti.ru." static
local-zone: "warfiles.ru." static
